### ISSUE TITLE
Integrate recommender system

### ISSUE THREAD

**Issue by husak** [CSIRT-MU/CRUSOE#2]
Integrate recommender system from https://github.com/CSIRT-MU/recommender-system-for-network-security-management

I am looking for a more elegant solution than simply copying the code from one repo to a directory in another repo, e.g., with keeping history - development of the recommender system can then continue as a part of crusoe and the original repo will be locked as a version published with the research paper.

After integration, there is also a need to:
- update all paths, URLs, API locations, etc.
- update automated deployment (ansible, docker) to include also the recommender system

**Comment by michal-cech** [comment]
Recommender was successfully moved to recommender_system directory in the `crusoe_update` branch. The history was kept.

**Comment by michal-cech** [comment]
The updates and deployment are yet to be done.

**Comment by michal-cech** [comment]
Simple Vagrant & Ansible and Dockerfile done. Locations in other projects were (hopefully) patched
